Repository owncloud/data_exporter, pull requests merged in 2019-07, with the labels that each got.

#85 fix bootstap according to new standard
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 3 - To review, QA-Team, dev:acceptance-tests

#84 data_exporter app test against latest tarball
  .drone.yml
Labels: 3 - To review, QA-Team, dev:acceptance-tests

#88 Copy Password for DB users
  lib/Command/ExportUser.php
  lib/Extractor/MetadataExtractor/UserExtractor.php
  lib/Extractor/MetadataExtractor/UserExtractor/GetPasswordHashQuery.php
  lib/Importer/MetadataImporter/UserImporter.php
  lib/Importer/MetadataImporter/UserImporter/UpdatePasswordHashQuery.php
  lib/Model/User.php
  tests/integration/MetadataImportExportTest.php
  tests/integration/UserImporterTest.php
  tests/unit/Extractor/MetadataExtractor/UserExtractorTest.php
  tests/unit/Importer/MetadataImporter/UserImporterTest.php
Labels: 3 - To review

#91 Bump symfony (v3.4.28 => v3.4.30)
  composer.lock
Labels: 3 - To review

#92 Remove stable10 test jobs
  .drone.yml
Labels: 4 - To release, QA-Team
