Repository owncloud/data_exporter, pull requests merged in 2019-08, with the labels that each got.

#99 Use only 1 var in when matrix of drone
  .drone.yml
Labels: 4 - To release, QA-Team

#100 Add unit tests on PHP 7.3
  .drone.yml
Labels: 3 - To review, QA-Team

#102 use the correct oC version to run tests
  .drone.yml
Labels: 4 - To release, QA-Team, dev:acceptance-tests
