Repository owncloud/data_exporter, pull requests merged in 2019-01, with the labels that each got.

#62 Install and run behat from vendor-bin
  Makefile
  tests/acceptance/config/behat.yml
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-Team, dev:acceptance-tests

#57 Create dist Target, separate makefile
  Makefile
  Makefile.release
Labels: 3 - To review, enhancement

#58 Preserve the link token and fix the password handling.
  Makefile
  docs/manual.md
  lib/Exporter/MetadataExtractor/SharesExtractor.php
  lib/Importer/MetadataImporter/ShareImporter.php
  lib/Model/User/Share.php
  tests/unit/Exporter/MetadataExtractor/SharesExtractorTest.php
  tests/unit/Importer/MetadataImporter/ShareImporterTest.php
Labels: 2 - Developing, bug, enhancement
