Repository owncloud/data_exporter, pull requests merged in 2020-04, with the labels that each got.

#151 Bump phpstan 0.12
  appinfo/register_command.php
  lib/Command/MigrateShare.php
  lib/Importer/FilesImporter.php
  lib/Importer/TrashBinImporter.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 3 - To review

#150 Bump symfony dependencies
  composer.lock
Labels: 3 - To review

#153 [Tests-Only] Bump phan 2.7
  lib/Utilities/Iterators/Nodes/RecursiveNodeIterator.php
  vendor-bin/phan/composer.json
Labels: QA-Team

#152 [Tests-Only] Export user with multiple files in trashbin
  .drone.star
  composer.json
  composer.lock
  tests/acceptance/features/cliDataExporter/export.feature
Labels: 4 - To release, QA-Team, dev:acceptance-tests

#156 Implement phpunit v8
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-Team

#157 Adjust drone pipelines for PHP 7.4
  .drone.star
  .gitignore
Labels: 3 - To review, QA-Team
