Repository owncloud/data_exporter, pull requests merged in 2020-03, with the labels that each got.

#146 Update PHP symfony and other dependencies
  composer.lock
Labels: 3 - To review

#147 Pin behat/mink to 1.7.1 and update other acceptance test dependencies
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-Team, dev:acceptance-tests

#149 [Tests-Only] Export user with file in trashbin
  tests/acceptance/features/bootstrap/DataExporterContext.php
  tests/acceptance/features/cliDataExporter/export.feature
Labels: 4 - To release, QA-Team, dev:acceptance-tests
