Repository owncloud/data_exporter, pull requests merged in 2020-05, with the labels that each got.

#154 [Tests-Only] Restoring and renaming files in trashbin
  tests/acceptance/data/simpleExport/testUser/files.jsonl
  tests/acceptance/data/simpleExport/testUser/files/newFolder/'quotes1'
  tests/acceptance/data/simpleExport/testUser/files/newFolder/strängé नेपाली file
  tests/acceptance/data/simpleExport/testUser/files/newFolder/testFolder/T1/T2/afile.txt
  tests/acceptance/data/simpleExport/testUser/files_trashbin/trashFolder.d1587631996/T1/T2/fileinfolder.txt
  tests/acceptance/data/simpleExport/testUser/shares.jsonl
  tests/acceptance/data/simpleExport/testUser/trashbin.jsonl
  tests/acceptance/data/simpleExport/testUser/user.json
  tests/acceptance/features/cliDataExporter/import.feature
Labels: 4 - To release, QA-Team, dev:acceptance-tests

#158 Update symfony to 3.4.40
  composer.lock
Labels: 3 - To review

#159 [Tests-Only] Fix unit tests related to core issue 37358 and core PR 37103
  tests/unit/Extractor/MetadataExtractor/UserExtractorTest.php
Labels: 3 - To review

#160 Use plugins/codecov:latest
  .drone.star
Labels: 3 - To review, QA-Team

#161 Use realistic usernames
  tests/acceptance/features/bootstrap/DataExporterContext.php
  tests/acceptance/features/cliDataExporter/export.feature
  tests/acceptance/features/cliDataExporter/import.feature
Labels: 3 - To review, QA-Team, dev:acceptance-tests
