Repository owncloud/data_exporter, pull requests merged in 2020-02, with the labels that each got.

#139 Add phpdoc for Symfony Command execute
  lib/Command/ExportUser.php
  lib/Command/ImportUser.php
Labels: 3 - To review

#141 Update starlark code 20200208
  .drone.star
  .drone.yml
Labels: 3 - To review, Drone, QA-Team

#142 Fix passwordHash can be null during deserialization
  lib/Model/User.php
Labels: bug

#143 [Tests-only] guzzle version updated
  vendor-bin/behat/composer.json
Labels: QA-Team

#144 NC export
  appinfo/info.xml
  lib/Extractor/MetadataExtractor/SharesExtractor.php
  tests/unit/Extractor/MetadataExtractor/SharesExtractorTest.php
Labels: enhancement
